# This is a basic workflow to help you get started with Actions

name: Build CNS.Auth.Web

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - main
    paths:
    - 'WebApps/CNS.Auth.Web/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    env:
      SOLUTION_FILE: "CNS.Auth.Web.sln"
      PUBLISH_FOLDER: "_publish"
      ARTIFACT_NAME: CNSProxy
      RELEASE_VERSION: 8.0.${{ github.run_number}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApps/CNS.Auth.Web
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 8.x
          dotnet-quality: ga

      - name: publish
        run: dotnet publish -c Release -o $PUBLISH_FOLDER -p:Version=$RELEASE_VERSION $SOLUTION_FILE
      - name: Upload Build Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/WebApps/CNS.Auth.Web/${{ env.PUBLISH_FOLDER }}
