# This is a basic workflow to help you get started with Actions

name: Build and Release SPIDProxy

# Controls when the workflow will run
on:
  push:
    branches:
    - main
    paths:
    - 'WebApps/Proxy/**'
    - 'WebApps/Microsoft.SPID.Proxy.sln'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BuildAndRelease:
    permissions:
      contents: write
    env:
      SOLUTION_FILE: "Microsoft.SPID.Proxy.sln"
      PUBLISH_FOLDER: "_publish"
      ARTIFACT_NAME: SPIDProxy
      RELEASE_VERSION: 8.0.${{ github.run_number}}
      RELEASE_ZIP_FILENAME: "release.zip"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApps/Proxy
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 8.0.x

      - name: publish
        run: dotnet publish -c Release -o $PUBLISH_FOLDER -p:Version=$RELEASE_VERSION $SOLUTION_FILE

      - name: Upload Build Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/WebApps/Proxy/${{ env.PUBLISH_FOLDER }}
      
      - name: Zip Release
        uses: TheDoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554 # 0.7.6
        with:
          directory: ${{ github.workspace }}/WebApps/Proxy/${{ env.PUBLISH_FOLDER }}
          filename: ${{ github.workspace }}/WebApps/Proxy/${{ env.PUBLISH_FOLDER }}/${{ env.RELEASE_ZIP_FILENAME }}
      
      - name: Create Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: ${{ github.workspace }}/WebApps/Proxy/${{ env.PUBLISH_FOLDER }}/${{ env.RELEASE_ZIP_FILENAME }}
          commit: ${{ github.sha }}
          tag: v${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
