# This is a basic workflow to help you get started with Actions

name: Build SPIDProxy

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - main
    paths:
    - 'WebApps/Proxy/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    env:
      SOLUTION_FILE: "Microsoft.SPID.Proxy.sln"
      PUBLISH_FOLDER: "_publish"
      ARTIFACT_NAME: "SPIDProxy"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApps/Proxy
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: publish
        run: dotnet publish -c Release -o $PUBLISH_FOLDER $SOLUTION_FILE

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/WebApps/Proxy/${{ env.PUBLISH_FOLDER }}
